### PR TITLE
Add iteration over `FrozenHashMap`

### PR DESCRIPTION
**Pull request by oli-cosmian**

### CODE REVIEW

**Comment by Manishearth** [comment]
I don't think I like this approach: the `in_use` is a reentrancy guard specifically to prevent weird trait impls from breaking this, it should not actually be load-bearing in normal Rust code.

**Comment by oli-cosmian** [comment]
I'm not too happy about it either, but the other approaches are equally uncool:

* keep a `HashSet` of keys in userspace
* compute the `HashSet` of key before iteration in `elsa`
* keep an index and restart iteration + skip `index` elements at each `next` call.

None of these solutions appeal to me.

Also: there's precedent in other languages for this. The GNAT Ada standard library's container iterators all have such a panicking/throwing runtime guard (the guard is used for both weird impls and normal code)

**Comment by bjorn3** [comment]
Maybe take `&mut self` when creating the iter, so that `insert` is blocked?

**Comment by oli-cosmian** [comment]
I don't have  `&mut self` access at the use site, but I guess I could move back to mutable references...

**Comment by oli-cosmian** [comment]
Ok, I tried that, that won't work as my use case requires functions to be able to take a `Foo<'a>` and `&'a elsa::FrozenHashMap<A, B>` as arguments and return `Something<'a>`, where the `Something` may arbitrarily reborrow borrow from the `Foo<'a>`'s things and intern things via `elsa`. If I pass down the `FrozenHashMap` via a mutable reference I'd need to make all functions that take such a reference also return it again and do a crazy reassignment dance at all call sites

**Comment by oli-cosmian** [comment]
I can't come up with a scheme that does not lock the `in_use` guard.

**Pull request closed without merging**
